# Generated by Django 3.1.1 on 2020-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='test',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
