# Generated by Django 3.1 on 2021-03-15 21:27

import backend_django.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0002_auto_20200908_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='competitors',
            field=models.JSONField(default=backend_django.utils.defaultCompetitorValues),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_quarter_chart',
            field=models.JSONField(default=backend_django.utils.defaultValues),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_modified',
            field=models.JSONField(default=backend_django.utils.defaultValues),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_quarter_chart',
            field=models.JSONField(default=backend_django.utils.defaultValues),
        ),
    ]
