# Generated by Django 3.2.5 on 2021-08-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0004_companylike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-g_true']},
        ),
    ]
