# Generated by Django 3.2.5 on 2021-08-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='company',
            index_together={('google_industry', 'industry')},
        ),
    ]
