# Generated by Django 3.2.5 on 2021-08-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0006_alter_company_index_together'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE backend_django_company ADD FULLTEXT `name` (`name`(255));"
        ),
    ]