# Generated by Django 3.2.5 on 2022-02-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0007_auto_20210816_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('annual_revenue',)},
        ),
        migrations.AlterIndexTogether(
            name='company',
            index_together=set(),
        ),
    ]
