# Generated by Django 3.2.5 on 2022-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0008_auto_20220203_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]