# Generated by Django 3.0.10 on 2021-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/home/Konaequity/konaequity/media/profile_photos/generic.png', upload_to='profile_photos/'),
        ),
    ]
