# Generated by Django 3.2.5 on 2021-12-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/home/kasashino/workshop/Django/konaequity/media/profile_photos/generic.png', upload_to='profile_photos/'),
        ),
    ]
