# Generated by Django 3.2.5 on 2022-04-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_auto_20220203_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pageview',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/Users/boiyelove/Documents/Development/konaequity/media/profile_photos/generic.png', upload_to='profile_photos/'),
        ),
    ]
